### PR TITLE
Third party monitoring tools

### PR DESCRIPTION
**Pull request by actuallymentor**
Added some basic and more advanced options to monitor the state of a Rocket Pool node.

### CODE REVIEW

**Comment by actuallymentor** [comment]
@jclapis this is ready from my end. Let me know if you would like any additions or edits.

Thanks for the second pair of eyes Yorrick.

**Comment by jclapis** [comment]
Wow, this is pretty comprehensive, great work Mentor! Quick question before I get too far into it:

image

Can you tell me why `updates.md` got moved into the `images` folder?

**Comment by actuallymentor** [comment]
@jclapis no idea where that came from, undid it :)

**Comment by jclapis** [comment]
Thank you for putting this together Mentor! I'll put together an announcement for it after I've had time to play with these options a bit.

**Pull request merged**
