### PR TITLE
Added glossary.md

### PR DESCRIPTION
**Pull request by htimsk**
Provides a glossary of common Rocket Pool terms for reference by readers of the documentation repository.

### CODE REVIEW

**Comment by actuallymentor** [comment]
Hey @htimsk!

Good idea to add this to the documentation. Only adding the `md` doesn't give it a place in the menu though which makes it hard to find if you're not looking for it.

I think it would be a good idea to add `glossary` to `src/.vuepress/config.js` around line 88 under `children`. Have a look whether your item shows up in the sidebar and if so push to additional change to this PR.

**Comment by htimsk** [comment]
I just read this comment. Let work on this today and figure out how to do this.

**Comment by htimsk** [comment]
I've got to get better at figuring out git hub and how to get it to sync/fetch/pull correctly between my Linux box, my pc, my clone of the docs repo, and this repository. (I'll carve some time to learn it better. I updated the pull request with an updated config.js that added the 'Glossary" to the left-hand table of contents as mentor suggested and cleaned the glossary formatting to make it look a little better. I'm hoping that you can see these changes on your end. - Ken

**Comment by actuallymentor** [comment]
Looks good! If you ever have questions about any part of this process feel free to reach out to me here or on the discord.

@darcius would love to hear your feedback on this PR by @htimsk, it currently:

- [x] Adds a glossary of terms often discussed in the Discord
- [x] Adds the glossary to the docs menu without an emoji

**Comment by darcius** [comment]
Looks great to me guys, thanks for vetting @actuallymentor and for the work @htimsk!

**Pull request merged**
