### PR TITLE
Adding 2FA to the security guide

### PR DESCRIPTION
**Pull request by actuallymentor**
- [ ] install GAuth PAM
- [ ] config `PAM` and `sshd` to play nice
- [ ] make sure ssh key is respected, but password is not asked, but 2fa is

Tested on Ubuntu `2004 LTS`

### CODE REVIEW

**Comment by jclapis** [comment]
Hey Mentor, we have a convention where new sentences all begin on a new line. Can you reformat this a bit to follow that before I merge it?

**Comment by actuallymentor** [comment]
Unless I misunderstand, every sentence starts on a newline? What am I missing?

**Comment by actuallymentor** [comment]
Added newlines!

**Comment by jclapis** [comment]
Done and done. Thanks Mentor!

**Pull request merged**
